name: flutter_click_more_counter
description: "A Flutter plugin for handle the click action, you can hidden something content in your app for debug, tracking issue"
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0